[fix] `com.apple.eawt` loading
Fixes

```
java.lang.IllegalAccessException: class org.jdesktop.application.utils.OSXAdapter cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @30a3107a
```